export const reportData = {
  generatedAt: '2026-05-22 KST',
  codex: {
    lane: 'Codex',
    folder: '태양계프로젝트 - codex',
    branch: 'codex',
    remote: 'not configured',
    currentStep: 'Step 4',
    latestImplementationCommit: 'aa5cad8 Upgrade simulator interaction and visuals',
    latestTrackingCommit: '7c586c4 Track Claude solar project progress',
    appUrl: './index.html',
    strengths: [
      'Date-object based ephemeris path is retained for planet and Moon placement.',
      'Baseline reset is fixed to 2026-05-22 as requested.',
      'Playwright verification covers desktop/mobile rendering, date jumps, speed presets, click focus, info panel, and overview return.',
      'Code is separated into HTML, CSS, app JS, report JS, and data files for maintainability.',
      'Peer tracking is recorded under internal/peer without modifying the Claude folder.',
    ],
    openItems: [
      'Remote repository is not configured yet, so Codex commits are local only.',
      'Tide mode is intentionally not promoted until harmonic constants and local corrections are specified.',
      'Next recommended slice: source/accuracy panel and high-precision lunar/tide module.',
    ],
  },
  claude: {
    lane: 'Claude',
    folder: 'solar-system',
    branch: 'master',
    remote: 'https://github.com/gmpark-creator/solar-system.git',
    currentStep: 'Step 4',
    localHead: '776f71fe4596d463412f9ba161c92268c0c78e32',
    remoteHead: '776f71fe4596d463412f9ba161c92268c0c78e32',
    liveUrl: 'https://gmpark-creator.github.io/solar-system/',
    reportSource: '../solar-system/README.md',
    strengths: [
      'GitHub remote is configured and origin/master matches local HEAD.',
      'README report documents Steps 1-4 and provides a GitHub Pages URL.',
      'Step 3 includes a theoretical tide visualization, tide panel, and 48-hour curve.',
      'Step 4 adds time-machine controls, interaction, sidebar profile, labels, and shadows.',
    ],
    concerns: [
      'README describes reset as today reset; fixed 2026-05-22 baseline should be confirmed if required.',
      'Tide output is equilibrium-tide visualization, not an operational harbor tide table.',
      'Implementation remains mostly single-file index.html, which may become harder to test as scope grows.',
      'Direct Math.random usage appears in visuals, so screenshot evidence may vary between reloads.',
      'Earth rotation appears to use a simplified formula instead of Julian Date GMST.',
    ],
  },
  metrics: [
    { label: 'Bodies Rendered', value: '10', detail: 'Sun, Moon, Earth, 7 additional planets' },
    { label: 'Codex Verification', value: 'PASS', detail: 'Desktop/mobile Playwright checks' },
    { label: 'Claude Remote', value: 'Synced', detail: 'origin/master equals local HEAD' },
    { label: 'Baseline Date', value: '2026-05-22', detail: 'Fixed reset in Codex lane' },
  ],
  timeline: [
    {
      step: 'Step 1',
      title: 'Sun, Earth, Moon foundation',
      date: '2026-05-21',
      codex: ['Three.js scene', 'OrbitControls', 'Sun/Earth/Moon', 'GMST Earth rotation', 'Moon perturbation model'],
      claude: ['Space background', 'Camera controls', 'Sun/Earth/Moon real-time implementation'],
    },
    {
      step: 'Step 2',
      title: 'Major planet expansion',
      date: '2026-05-21',
      codex: ['7 additional major planets', 'Keplerian positions', 'Orbit lines', 'Focus dropdown', 'Saturn ring'],
      claude: ['8-planet expansion', 'Keplerian ephemeris', 'Saturn rings', 'Earth texture upgrade'],
    },
    {
      step: 'Step 3',
      title: 'Time navigation and tide track split',
      date: '2026-05-22',
      codex: ['Direct datetime input', '+/- day controls', '+/- 730 day slider', 'Live reset', 'Time-control verification'],
      claude: ['Theoretical tide panel', 'Tidal bulge', '48-hour curve', 'Web deployment'],
    },
    {
      step: 'Step 4',
      title: 'Interaction and visual upgrade',
      date: '2026-05-22',
      codex: ['Fixed 2026-05-22 reset', 'Calendar jump buttons', '1x/10x/100x presets', 'Click focus', 'Info panel', 'Shadows and ring texture'],
      claude: ['Time-machine UI', 'Speed slider', 'Click interaction', 'Info sidebar', 'Labels', 'Shadow map'],
    },
  ],
  verification: [
    'npm run verify passes for the simulator.',
    'Desktop viewport 1440x900 renders nonblank canvas with expected controls.',
    'Mobile viewport 390x844 renders nonblank canvas with wrapped controls.',
    'Date reset returns to 2026-05-22.',
    '+1 week jump resolves to 2026-05-29.',
    '100x speed preset readout is verified.',
    'Earth click focus opens the information panel.',
    'Overview return hides the panel and focuses the Sun.',
  ],
  redTeam: [
    'Do not treat either lane tide visualization as operational tide prediction until local harmonic constants are introduced.',
    'Keep Claude folder read-only from Codex; cross-review through git/README/browser evidence only.',
    'Codex needs a remote before push can happen automatically.',
    'Before merging lanes, compare reset semantics, Earth rotation formula, and tide accuracy claims.',
  ],
};
